const SET_LANGUAGE = "SET_LANGUAGE";
const FETCH_BEGIN = "FETCH_BEGIN";
const FETCH_SUCCESS = "FETCH_SUCCESS";
const FETCH_ERROR = "FETCH_ERROR";

export { SET_LANGUAGE, FETCH_BEGIN, FETCH_SUCCESS, FETCH_ERROR };
